### PR TITLE
Differentiate mac, mac private, and windows start scripts

### PR DESCRIPTION
**Pull request by pRizz**

### CODE REVIEW

**Comment by ntheile** [comment]
awesome man! i didnt know you could specify OS

**Comment by pRizz** [comment]
Yeah man, it’s arbitrary. You can make scripts called `start:super:awesome:program`

**Comment by ntheile** [comment]
i'm just stoked i have a second contributor lol 👨‍💻 👨‍💻

**Comment by ntheile** [comment]
darn, it actually does not detect os...lol

**Pull request merged**
